/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Data5 {
    /**
     * 
     */
    password: string;

    /**
     * 
     */
    first_name?: string;

    /**
     * 
     */
    profile: any;

    /**
     * 
     */
    email?: string;

    /**
     * 
     */
    last_name?: string;

    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;

}
